AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'config/routes.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case
Naming/FileName:
  Enabled: false

Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: [context, describe]
  Max: 50
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

ParameterLists:
  Max: 5
  CountKeywordArgs: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/AccessModifierIndentation:
  EnforcedStyle: indent
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
